# Generated by Django 2.2.5 on 2020-05-23 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=5)),
                ('currentPopulation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('population', models.IntegerField()),
                ('date', models.DateField()),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthHack.company')),
            ],
        ),
        migrations.CreateModel(
            name='dailyAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('population', models.IntegerField()),
                ('count', models.IntegerField()),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthHack.company')),
            ],
        ),
    ]
