# Generated by Django 2.2.5 on 2020-05-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthHack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(default='Grocery', max_length=30),
            preserve_default=False,
        ),
    ]
