# Generated by Django 2.2.5 on 2020-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthHack', '0002_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='key',
            field=models.CharField(default='123456789', max_length=20),
            preserve_default=False,
        ),
    ]
